version: '3.8'
services:
  server:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/server
      - /server/node_modules
    command:
      npm run dev
    ports:
      - "3001:3001"
    environment:
      DEBUG: nodejs-docker-express:*
  auth:
    build:
      context: ./auth
      target: dev
    volumes:
      - ./auth:/auth
      - /auth/node_modules
    command:
      npm run dev
    ports:
      - "4001:4001"
    environment:
      DEBUG: nodejs-docker-express:*
    depends_on:
      - redis
  # client:
  #   image: node:lts
  #   restart: on-failure
  #   container_name: client_container
  #   working_dir: /client
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./client:/client
  #     - type: bind
  #       source: ./server
  #       target: /server
  #   command: npm run dev
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - server
      - auth
