version: '3.8'
services:
  server:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - "3001:3001"
    environment:
      DEBUG: nodejs-docker-express:*
  auth:
    build:
      context: ./auth
      target: dev
    volumes:
      - ./auth:/auth
      - /auth/node_modules
    ports:
      - "4001:4001"
    environment:
      DEBUG: nodejs-docker-express:*
    depends_on:
      - redis
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    ports: 
      - "80:80"
    depends_on:
      - server
      - auth
