version: '3.8'
services:
  server:
    build:
      target: production
    environment:
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
  auth:
    build:
      target: production
    environment:
      - CLIENT_DOMAIN=${CLIENT_DOMAIN}
  nginx:
    build: 
      target: production
