name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install node

      - name: Build frontend

      - name: Set up SSH Key

      - name: SSH into EC2

      - name: Install Docker

      - name: Run Docker Compose Script

